name: CI-Front

on:
  push:
    branches: [main, feature/**]
    paths:
      - 'sources/gui/**'
  pull_request:
    branches: [main]
    paths:
      - 'sources/gui/**'

jobs:
  build:
    defaults:
      run:
        working-directory: ./sources/gui/Ggio.BikeSherpa.Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: sources/gui/Ggio.BikeSherpa.Frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v6
        with:
          name: frontend-artifact
          path: |
            sources/gui/Ggio.BikeSherpa.Frontend
            !sources/gui/Ggio.BikeSherpa.Frontend/node_modules
  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./sources/gui/Ggio.BikeSherpa.Frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: sources/gui/Ggio.BikeSherpa.Frontend/package-lock.json
      
      - name: Download frontend artifact
        uses: actions/download-artifact@v6
        with:
          name: frontend-artifact
          path: .
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage
        run: npm run test -- --coverage --coverageDirectory=./.qodana/code-coverage
      
      - name: Upload coverage reports
        uses: actions/upload-artifact@v6
        with:
          name: frontend-coverage
          path: sources/gui/Ggio.BikeSherpa.Frontend/.qodana/code-coverage