name: CI-Front

on:
  push:
    branches: [main, feature/**]
    paths:
      - 'sources/gui/**'
  pull_request:
    branches: [main]
    paths:
      - 'sources/gui/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sources/gui/Ggio.BikeSherpa.Frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('sources/gui/Ggio.BikeSherpa.Frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test
      
      - name: Archive coverage data
        uses: actions/upload-artifact@v6
        with:
          name: jest-coverage-data
          path: sources/gui/Ggio.BikeSherpa.Frontend/.qodana/code-coverage

      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
         QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_TS }}
        with:
          args: "-i,sources/gui/Ggio.BikeSherpa.Frontend,--image,jetbrains/qodana-js:2025.3"
          pr-mode: false
